const D=window.SEABIRD_DATA, by=id=>document.getElementById(id), state={current:null,window:null,challenge:null,windowGuess:null,challengeGuess:null,total:0,right:0,seen:new Set(),matrix:'xgboost'};
const labelMap=Object.fromEntries(D.classes.map(x=>[x.key,x.name]));
function pick(cls){const pool=D.samples.filter(s=>!cls||s.class===cls), s=pool[Math.floor(Math.random()*pool.length)];return s}
function chart(canvas,s){if(!canvas||!s)return;const ratio=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext('2d');c.scale(ratio,ratio);c.clearRect(0,0,w,h);const vals=[...s.x,...s.y,...s.z],mn=Math.min(...vals),mx=Math.max(...vals),pad=28,span=mx-mn||1;c.strokeStyle='#dbe5e2';c.lineWidth=1;for(let i=0;i<5;i++){let y=pad+(h-pad*2)*i/4;c.beginPath();c.moveTo(pad,y);c.lineTo(w-pad,y);c.stroke()}[['x','#ef775f'],['y','#13a4a0'],['z','#345fbb']].forEach(([k,color])=>{c.beginPath();s[k].forEach((v,i)=>{let x=pad+(w-pad*2)*i/(s[k].length-1),y=h-pad-(v-mn)/span*(h-pad*2);i?c.lineTo(x,y):c.moveTo(x,y)});c.strokeStyle=color;c.lineWidth=2;c.stroke()});c.fillStyle='#647a7e';c.font='11px system-ui';c.fillText('0 s',pad,h-7);c.fillText('2 s',w-pad-18,h-7)}
function go(id){location.hash=id;by(id).scrollIntoView({behavior:'smooth'});state.seen.add(id);progress()}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.querySelectorAll('.mode-switch button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(b.dataset.mode==='guided'?'已切换：跟着步骤学':'已切换：自由探索，可从侧边栏跳转')});
function progress(){const n=Math.min(6,[...state.seen].filter(x=>x!=='home').length);by('progressBar').style.width=n/6*100+'%';by('progressText').textContent=n?`${n} / 6 已探索`:'0 / 6 尚未开始'}
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id));if(e.target.id!=='home'){state.seen.add(e.target.id);progress()}}}),{threshold:.35});document.querySelectorAll('.station').forEach(s=>obs.observe(s));
function fillChoices(id,handler){by(id).innerHTML=D.classes.map(c=>`<button data-key="${c.key}">${c.name}</button>`).join('');by(id).querySelectorAll('button').forEach(b=>b.onclick=()=>{by(id).querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');handler(b.dataset.key)})}
const sel=by('dataClass');sel.innerHTML=D.classes.map(c=>`<option value="${c.key}">${c.name}</option>`).join('');
function setData(){state.current=pick(sel.value);by('dataSampleId').textContent=state.current.id;by('dataAnimal').textContent=`个体 ${state.current.animal} · ${state.current.time}`;chart(by('dataChart'),state.current)} sel.onchange=setData;by('newDataSample').onclick=setData;setData();
by('intensity').querySelectorAll('button').forEach(b=>b.onclick=()=>{by('intensity').querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');b.parentElement.nextElementSibling.hidden=false});
function newWindow(){state.window=pick();state.windowGuess=null;chart(by('windowChart'),state.window);chart(by('xgbChart'),state.window);chart(by('dclChart'),state.window);by('windowAnswer').hidden=true;by('revealWindow').disabled=true;by('windowChoices').querySelectorAll('button').forEach(x=>x.classList.remove('selected'));by('featurePanel').classList.add('muted');by('featurePanel').innerHTML='<h3>代表性特征</h3><p>点击左侧按钮，看看这段曲线会变成哪些数字。</p>';by('allFeatures').innerHTML=''}
fillChoices('windowChoices',k=>{state.windowGuess=k;by('revealWindow').disabled=false});by('generateWindow').onclick=newWindow;newWindow();by('revealWindow').onclick=()=>{const ok=state.windowGuess===state.window.class;by('windowAnswer').innerHTML=`<b>${ok?'你猜对了。':'这并不容易只靠肉眼判断。'}</b><br>真实行为：${state.window.label}${ok?'':'。这正是我们需要机器学习的原因。'}`;by('windowAnswer').hidden=false};
const explanations={VeDBA_mean:'运动整体有多剧烈',VeDBA_var:'运动强度变化有多大',pitch_var:'身体前后倾斜变化',roll_var:'身体左右倾斜变化',acc_x_dcp_mean:'前后方向的动态变化'};
by('makeFeatures').onclick=()=>{const f=state.window.features,keys=Object.keys(explanations);by('featurePanel').classList.remove('muted');by('featurePanel').innerHTML='<h3>这段曲线 → 119 个动作指标</h3>'+keys.map(k=>`<div class="feature-item"><div><b>${k}</b><span>${explanations[k]}</span></div><strong>${Number(f[k]).toFixed(4)}</strong></div>`).join('');by('allFeatures').innerHTML=Object.entries(f).map(([k,v])=>`<div><b>${k}</b><br>${v??'—'}</div>`).join('')};
const maxImp=Math.max(...D.importance.map(x=>x.value));by('importanceBars').innerHTML=D.importance.map(x=>`<div class="bar-row"><span>${x.name}</span><div class="bar-track"><i style="width:${x.value/maxImp*100}%"></i></div><b>${(x.value*100).toFixed(1)}%</b></div>`).join('');
by('modelGuess').querySelectorAll('button').forEach(b=>b.onclick=()=>{by('modelGuess').querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderMetrics();toast('继续看 Macro F1：少数类别也应该被同等重视')});
function renderMetrics(){const x=D.results.xgboost,d=D.results.dclsa,items=[['Accuracy','accuracy'],['Macro F1','macro_f1'],['Weighted F1','weighted_f1'],['Macro IoU','macro_iou']];by('metrics').innerHTML=items.map(([n,k])=>`<div class="metric"><span>${n}</span><b>${(x[k]*100).toFixed(1)}% <small>XGB</small></b><b class="dcl">${(d[k]*100).toFixed(1)}% <small>DCL-SA</small></b></div>`).join('')}renderMetrics();
function renderMatrix(){const r=D.results[state.matrix],m=r.matrix,max=Math.max(...m.flat()),names=D.classes.map(x=>x.name);let html='<div class="matrix"><div></div>'+names.map(n=>`<div class="label top">${n}</div>`).join('');m.forEach((row,i)=>{html+=`<div class="label">${names[i]}</div>`+row.map((v,j)=>`<div class="cell" title="真实 ${names[i]} → 预测 ${names[j]}：${v} 个" style="background:rgba(16,166,161,${.08+.9*v/max})">${v}</div>`).join('')});by('matrix').innerHTML=html+'</div>';const weak=[...r.per_class].sort((a,b)=>a.f1-b.f1)[0];by('weakness').innerHTML=`<b>模型的一个弱点</b><p><strong>${weak.label}</strong> 的 F1 最低（${(weak.f1*100).toFixed(1)}%）。少样本、短暂动作与相似波形都可能增加识别难度。</p>`}renderMatrix();document.querySelectorAll('.matrix-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.matrix-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.matrix=b.dataset.model;renderMatrix()});
function newChallenge(){state.challenge=pick();state.challengeGuess=null;chart(by('challengeChart'),state.challenge);by('challengeAnswer').hidden=true;by('challengeReveal').disabled=true;by('challengeChoices').querySelectorAll('button').forEach(x=>x.classList.remove('selected'))}fillChoices('challengeChoices',k=>{state.challengeGuess=k;by('challengeReveal').disabled=false});by('challengeReveal').onclick=()=>{state.total++;const ok=state.challengeGuess===state.challenge.class;if(ok)state.right++;by('humanScore').textContent=`你猜对了 ${state.right} / ${state.total}`;by('challengeAnswer').innerHTML=`${ok?'✓ 你和真实标签一致。':'这次没有猜中，也很正常。'}<br>你的判断：${labelMap[state.challengeGuess]}　·　真实行为：${state.challenge.label}`;by('challengeAnswer').hidden=false;by('challengeReveal').disabled=true};by('challengeNext').onclick=newChallenge;newChallenge();
function toast(t){const el=by('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}window.addEventListener('resize',()=>{chart(by('dataChart'),state.current);chart(by('windowChart'),state.window);chart(by('xgbChart'),state.window);chart(by('dclChart'),state.window);chart(by('challengeChart'),state.challenge)});
